apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 3                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: coit-frontend                                  # 6
        app.kubernetes.io/name: coit-frontend
    spec:
      serviceAccountName: coit-frontend
      volumes:
        - name: nginx-root
          persistentVolumeClaim:
            claimName: coit-frontend
        - name: datastore
          persistentVolumeClaim:
            claimName: coit-frontend-fast  
      containers:
        - image: vaibhavpancholi2/coit-frontend-kubernetes:v1
        # image: coitlearning/coit-frontend:v21
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-frontend
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 250M
            limits: 
              cpu: 150m
              memory: 450M
          # env:
          #   - name: JAVA_APP_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: coit-frontend-config
          #         key: JAVA_URL
          #   - name: SMS_API
          #     valueFrom:
          #       configMapKeyRef:
          #         name: values-from-props
          #         key: sms_provider_api

          # volumeMounts:
          #   - mountPath: /usr/share/nginx/html
          #     name: nginx-root
          #   - mountPath: /var/lib/sql
          #     name: datastore
  
